### ISSUE TITLE
BLE

### ISSUE THREAD

**Issue by craig-mulligan** [Agile-IoT/agile-resin#2]
@cskiraly, Tried getting agile core running on resinos today. I have got the api + protocal manager up, but couldn't get the BLE working. 

```
agile-core_1  | 13:50:01.766 [Thread-4] INFO  i.a.p.ProtocolManagerImp - Initializing discovery
agile-core_1  | 13:50:01.771 [Thread-4] INFO  i.a.p.ProtocolManagerImp - Discovery for protocol iot.agile.object.ProtocolOverview<BLE, Bluetooth LE, iot.agile.protocol.BLE, Avaliable> : /iot/agile/protocol/BLE
agile-core_1  | 13:50:01.837 [Thread-4] INFO  i.a.p.ProtocolManagerImp - BLE protocol is not supported
```

What is needed by the host to get the ble working? All I did was mount the system dbus. 

Sidenote: by using the docker-compose via a remote host I expect it won't be super hard to modify agile-scripts to work nicely with resinOS, we just need to point it to use DOCKER_HOST=tcp://resin.local:2375 :)

**Comment by cskiraly** [comment]
Current BLE version is set to run its own Bluez and its own DBUS inside the Docker container. This is a system DBUS for the docker image, but it is not for the system. We did it this way bacause Bluez is still too old on most host systems, and there were several API changes.

Therefore it needs:
- access to the bluetooth management socket
- no other bluez instance accessing that socket
Stop bluetoothd in the host, and give access to the networking stack. (network_mode="host" , https://github.com/Agile-IoT/agile-scripts/blob/61a53d79bc8e1bfa12339ca9e8653066eccbd234/compose/docker-compose.yml#L41).

As an alternative, if the host's version is new enough, we could also use that one, but that is a bit more tricky.

**Comment by craig-mulligan** [comment]
@cskiraly I'm running into the following error: 

```
agile-ble_1   | 15:25:22.810 [main] DEBUG i.agile.protocol.ble.BLEProtocolImp - Started BLE Protocol
agile-core_1  | Exception in thread "main" org.freedesktop.dbus.exceptions.DBusException: Failed to register bus name
agile-core_1  | 	at org.freedesktop.dbus.DBusConnection.requestBusName(Unknown Source)
agile-core_1  | 	at iot.agile.object.AbstractAgileObject.dbusConnect(AbstractAgileObject.java:25)
agile-core_1  | 	at iot.agile.protocol.ble.BLEProtocolImp.<init>(BLEProtocolImp.java:127)
agile-core_1  | 	at iot.agile.protocol.ble.BLEProtocolImp.main(BLEProtocolImp.java:123)
agile-core_1  | Jan 12, 2017 3:25:29 PM org.glassfish.jersey.internal.Errors logErrors
```

And when I check the services on the session bus, it looks like they are all there:

```
root@resin:/mnt/data/.agile/agile_bus# dbus-send --bus=unix:path=/mnt/data/.agile/agile_bus/agile_bus_socket       --dest=org.freedesktop.DBus   --type=method_call            --print-reply                 /org/freedesktop/DBus         org.freedesktop.DBus.ListNames
method return sender=org.freedesktop.DBus -> dest=:1.15 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string ":1.12"
      string ":1.13"
      string "iot.agile.DeviceManager"
      string ":1.8"
      string ":1.14"
      string ":1.9"
      string ":1.15"
      string "iot.agile.protocol.BLE"
      string "iot.agile.ProtocolManager"
   ]
```

Though it seems like this error can come from the service name already being registered. 

https://github.com/cathive/dbus-java/blob/master/src/main/java/org/freedesktop/dbus/DBusConnection.java#L455

The messages on the session bus stop after the exception is thrown, but I'm not sure what I should be looking for there.

Any ideas?

**Comment by craig-mulligan** [comment]
No worries, @cskiraly I've got it running. 👍
